[server]
port = 8503
headless = true
maxUploadSize = 500

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#CC0000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F8F8"
textColor = "#0A0A0A"
font = "sans serif"
